language: ruby
script: "bundle exec rake test"
env:
  - CI=true
rvm:
  - 1.8.7
  - rbx-19mode
  - jruby-19mode
  - jruby-head
  - 1.9.2
  - 1.9.3
gemfile:
  - Gemfile
notifications:
  recipients:
    - brent@brentium.com 
branches:
  only:
    - master
